name: selc_admin
description: "Administrator console to selc mobile application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.3.0
  provider: ^6.1.4
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  intl: ^0.20.2
  animations: ^2.0.11
  pdf: ^3.11.3
  file_picker: ^10.3.2
  excel: ^4.0.6
  contextmenu: ^3.0.0
  dio: ^5.9.0
  web_socket_client: ^0.2.1
  open_filex: ^4.7.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/imgs/
    

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600


